[package]
name = "package-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sudo = "0.6.0"
colored = "2.1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
git2 = "0.19.0"
